# Generated by Django 5.2.16 on 2026-08-01 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_extensionpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=32)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('requested_count', models.PositiveSmallIntegerField(default=1)),
                ('ready_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_jobs', to='control.clientaccess')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=32)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('proxy_fingerprint', models.CharField(max_length=64, unique=True)),
                ('profile_name', models.CharField(blank=True, max_length=160)),
                ('profile_id', models.CharField(blank=True, max_length=128)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_reservations', to='control.clientaccess')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='control.proxygenerationjob')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=64)),
                ('profile_name', models.CharField(blank=True, max_length=160)),
                ('profile_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(max_length=32)),
                ('start_urls_json', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_activity', to='control.clientaccess')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_activity', to='control.proxygenerationjob')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_activity', to='control.proxyreservation')),
            ],
        ),
    ]
