# Generated by Django 5.2.16 on 2026-08-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_proxygenerationjob_proxyreservation_profileactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyreservation',
            name='proxy_ciphertext',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
