# Generated by Django 5.2.16 on 2026-08-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_proxyreservation_proxy_ciphertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_group_id', models.CharField(max_length=64)),
                ('browser_group_name', models.CharField(max_length=160)),
                ('internal_name', models.CharField(help_text='Your private management label.', max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_groups', to='control.clientaccess')),
            ],
            options={
                'ordering': ('client__office_name', 'internal_name'),
                'constraints': [models.UniqueConstraint(fields=('client', 'browser_group_id'), name='unique_client_browser_group')],
            },
        ),
    ]
