# Generated by Django 5.2.16 on 2026-08-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_browsergroupmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxygenerationjob',
            name='status',
            field=models.CharField(default='queued', max_length=32),
        ),
    ]
