# Generated by Django 5.2.16 on 2026-08-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_proxygenerationjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_fingerprint', models.CharField(max_length=64, unique=True)),
                ('proxy_ciphertext', models.TextField(editable=False)),
                ('state', models.CharField(default='available', max_length=16)),
                ('exit_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fraud_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_entries', to='control.clientaccess')),
            ],
        ),
        migrations.AddField(
            model_name='proxyreservation',
            name='pool_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='control.proxypoolentry'),
        ),
        migrations.CreateModel(
            name='ProxyPoolTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=32)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('target_count', models.PositiveIntegerField(default=1000)),
                ('replenish_below', models.PositiveIntegerField(default=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_pool_targets', to='control.configbundle')),
            ],
        ),
        migrations.AddField(
            model_name='proxypoolentry',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='control.proxypooltarget'),
        ),
        migrations.AddConstraint(
            model_name='proxypooltarget',
            constraint=models.UniqueConstraint(fields=('config_bundle', 'provider_code', 'country_code', 'region', 'city'), name='unique_proxy_pool_target'),
        ),
    ]
