# Generated by Django 5.2.16 on 2026-08-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_subadminaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminDomainExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_exclusions', to='control.subadminaccount')),
            ],
            options={
                'verbose_name': 'Sub-admin domain exclusion',
                'verbose_name_plural': 'Sub-admin domain exclusions',
                'ordering': ('domain',),
                'constraints': [models.UniqueConstraint(fields=('account', 'domain'), name='unique_subadmin_domain_exclusion')],
            },
        ),
    ]
