# Generated by Django 5.2.16 on 2026-08-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_subadmindomainexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminScopeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('office', 'Office'), ('group', 'Browser group')], max_length=16)),
                ('value', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_exclusions', to='control.subadminaccount')),
            ],
            options={
                'verbose_name': 'Sub-admin scope exclusion',
                'verbose_name_plural': 'Sub-admin scope exclusions',
                'ordering': ('scope_type', 'value'),
                'constraints': [models.UniqueConstraint(fields=('account', 'scope_type', 'value'), name='unique_subadmin_scope_exclusion')],
            },
        ),
    ]
