# Generated by Django 5.2.16 on 2026-08-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_subadminscopeexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccessIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to='control.clientaccess')),
            ],
            options={
                'verbose_name': 'Additional client IPv4',
                'verbose_name_plural': 'Additional client IPv4s',
                'ordering': ('ipv4',),
                'constraints': [models.UniqueConstraint(fields=('client', 'ipv4'), name='unique_client_allowed_ipv4')],
            },
        ),
    ]
