# Generated by Django 5.2.16 on 2026-08-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_proxygenerationjob_submitted_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreateLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_key', models.CharField(max_length=180, unique=True)),
                ('owner_token', models.CharField(max_length=96)),
                ('group_id', models.CharField(max_length=64)),
                ('requested_count', models.PositiveSmallIntegerField(default=1)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_create_leases', to='control.clientaccess')),
            ],
            options={
                'ordering': ('expires_at',),
            },
        ),
    ]
