# Generated by Django 5.2.16 on 2026-08-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_profilecreatelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCreateQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(db_index=True, max_length=180)),
                ('request_token', models.CharField(max_length=96, unique=True)),
                ('lease_token', models.CharField(blank=True, default='', max_length=96)),
                ('group_id', models.CharField(max_length=64)),
                ('requested_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_create_queue', to='control.clientaccess')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['scope_key', 'status', 'created_at'], name='control_pro_scope_k_0f4a0c_idx')],
            },
        ),
    ]
