# Generated by Django 5.2.16 on 2026-09-02 06:07

import control.models
import control.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_proxy_exit_ip_cooldown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopComponentRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('ui', 'UI bundle'), ('engine', 'Action engine'), ('config', 'Application configuration'), ('bridge', 'Local Electron bridge'), ('browser', 'Browser package'), ('extension', 'Browser extension')], max_length=24)),
                ('slot', models.CharField(default='default', help_text='Use default for UI/engine/config/bridge; use the browser version or extension name for independently retained packages.', max_length=64, validators=[django.core.validators.RegexValidator(message='Use 1-64 letters, numbers, dots, underscores, or hyphens.', regex='\\A[A-Za-z0-9][A-Za-z0-9._-]{0,63}\\Z')])),
                ('channel', models.CharField(choices=[('public', 'Public'), ('testing', 'Testing')], default='public', max_length=16)),
                ('version', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Use 1-64 letters, numbers, dots, underscores, or hyphens.', regex='\\A[A-Za-z0-9][A-Za-z0-9._-]{0,63}\\Z')])),
                ('build_number', models.PositiveBigIntegerField(help_text='Monotonically increasing within this component and channel.', validators=[django.core.validators.MinValueValidator(1)])),
                ('activation', models.CharField(choices=[('hot', 'Apply on Reload'), ('bridge-restart', 'Apply after safe bridge restart'), ('app-restart', 'Apply after OPTIX restart')], default='hot', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('revoked', 'Revoked')], default='draft', editable=False, max_length=16)),
                ('target_offices', models.JSONField(blank=True, default=list)),
                ('target_device_ids', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-secret activation data. UI/engine/bridge ZIPs use entry; browser ZIPs use browser_version.')),
                ('artifact', models.FileField(storage=control.storage.PrivateDesktopReleaseStorage(), upload_to=control.models.desktop_component_artifact_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('zip', 'json'))])),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('artifact_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('artifact_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('signature_b64', models.TextField(blank=True, default='', help_text='Detached Ed25519 signature of the canonical component manifest.')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_component_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('component', '-build_number', '-pk'),
                'indexes': [models.Index(fields=['channel', 'status', 'component', 'slot', '-build_number'], name='component_release_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('component', 'slot', 'channel', 'build_number'), name='unique_component_release_build')],
            },
        ),
    ]
