# Generated by Django 5.2.16 on 2026-09-02 06:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_optix_runtime_configuration(apps, schema_editor):
    runtime = apps.get_model('control', 'DesktopRuntimeConfiguration')
    values = {
        'appName': 'OPTIX',
        'browsers': [
            {'id': 'B1', 'name': 'B1 - OPTIX Electron', 'enabled': True, 'order': 1},
            {'id': 'B2', 'name': 'B2 - Octo One-Time', 'enabled': True, 'order': 2},
        ],
        'devices': [
            {'id': 'desktop', 'name': 'Desktop', 'enabled': True, 'order': 1},
            {'id': 'mobile', 'name': 'Mobile', 'enabled': True, 'order': 2},
        ],
        'capabilities': {
            'browserSelector': True,
            'deviceSelector': True,
            'futureOsSelector': False,
            'futureBrowserVersionSelector': False,
        },
    }
    for channel in ('public', 'testing'):
        runtime.objects.get_or_create(
            channel=channel,
            defaults={'revision': 1, 'active': True, 'ui_config': values},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_desktop_component_releases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopRuntimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('public', 'Public'), ('testing', 'Testing')], max_length=16, unique=True)),
                ('revision', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('ui_config', models.JSONField(default=dict, help_text='Non-secret OPTIX UI data such as browsers, devices, labels, feature visibility and default selections. Changes apply through Reload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktop_runtime_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('channel',),
            },
        ),
        migrations.RunPython(seed_optix_runtime_configuration, migrations.RunPython.noop),
    ]
