# Generated by Django 5.2.16 on 2026-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_dollar_runtime_branding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desktopsecurityconfiguration',
            options={'verbose_name': 'Dollar desktop security', 'verbose_name_plural': 'Dollar desktop security'},
        ),
        migrations.AlterField(
            model_name='clientaccess',
            name='activation_mode',
            field=models.CharField(choices=[('inherit', 'Inherit global Dollar activation setting'), ('require', 'Require Dollar activation for this PC'), ('bypass', 'Legacy bypass — do not require Dollar activation')], default='inherit', help_text='Override the global Dollar activation requirement for this individual PC.', max_length=16),
        ),
        migrations.AlterField(
            model_name='desktopcomponentrelease',
            name='activation',
            field=models.CharField(choices=[('hot', 'Apply on Reload'), ('bridge-restart', 'Apply after safe bridge restart'), ('app-restart', 'Apply after Dollar restart')], default='hot', max_length=24),
        ),
        migrations.AlterField(
            model_name='desktopruntimeconfiguration',
            name='ui_config',
            field=models.JSONField(default=dict, help_text='Non-secret Dollar UI data such as browsers, devices, labels, feature visibility and default selections. Changes apply through Reload.'),
        ),
        migrations.AlterField(
            model_name='desktopsecurityconfiguration',
            name='activation_required',
            field=models.BooleanField(default=False, help_text='When enabled, every Dollar installation must present the current activation key.'),
        ),
        migrations.AlterField(
            model_name='desktopsecurityconfiguration',
            name='b1_enabled',
            field=models.BooleanField(default=False, help_text='Allow B1 (the local Dollar Electron bridge) for activated clients.'),
        ),
    ]
