# Generated by Django 5.2.16 on 2026-09-03 19:03

import control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_dollar_admin_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopOfficeAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('allowed_provider_codes', models.JSONField(blank=True, default=control.models.default_desktop_provider_codes)),
                ('allowed_browser_codes', models.JSONField(blank=True, default=control.models.default_desktop_browser_codes)),
                ('allowed_device_codes', models.JSONField(blank=True, default=control.models.default_desktop_device_codes)),
                ('show_logs', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desktop office access policy',
                'verbose_name_plural': 'Desktop office access policies',
                'ordering': ('office_name',),
            },
        ),
        migrations.AddField(
            model_name='clientaccess',
            name='allowed_browser_codes',
            field=models.JSONField(blank=True, default=list, help_text='Exact browser adapters allowed when the per-PC override is enabled.'),
        ),
        migrations.AddField(
            model_name='clientaccess',
            name='allowed_device_codes',
            field=models.JSONField(blank=True, default=list, help_text='Exact profile devices allowed when the per-PC override is enabled.'),
        ),
        migrations.AddField(
            model_name='clientaccess',
            name='allowed_provider_codes',
            field=models.JSONField(blank=True, default=list, help_text='Exact providers allowed when the per-PC override is enabled.'),
        ),
        migrations.AddField(
            model_name='clientaccess',
            name='desktop_permissions_override',
            field=models.BooleanField(default=False, help_text='When enabled, this PC uses the provider/browser/device/log permissions below instead of its office policy.'),
        ),
        migrations.AddField(
            model_name='clientaccess',
            name='show_logs_override',
            field=models.BooleanField(default=False, help_text='Show the Logs tab on this PC when the per-PC override is enabled.'),
        ),
    ]
